# Generated by Django 4.2.11 on 2025-03-02 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='bid_listing', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
