# Generated by Django 4.2.11 on 2025-03-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='comment_listing', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
